
name: Update Readme
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update Readme
        run: |
          pip3 install -r requirements.txt
          python3 .github/workflows/update_readme.py
      
      - name: Commit and push if changed
        env:
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --local user.name "Automated Readme Update"
          git config --local user.email "$EMAIL"
          git add README.md
          git commit -m "Update README.md"
          git push
